### ISSUE TITLE
How to implement?

### ISSUE THREAD

**Issue by henrikfiedler** [Clashsoft/bootstrap-darkmode#15]
Hey there,
I was looking for a bootstrap dark mode switcher and found yours and was really happy about it. However I honestly don't understand how to implement it. In your description and also on the demo page you are using .js files but now there are only .ts files in the repo. I tried it with some sort of js-ts-compiler but didn't succeed.
Do you have any instructions for me?

**Comment by Clashsoft** [comment]
Hi, thanks for your issue! Initially I started with JS but at some point transitioned to TypeScript, but I forgot to update the instructions accordingly. I'll make sure to update the Readme and let you know when it's done!

**Comment by henrikfiedler** [comment]
would be amazing. Looking forward to use your dark mode soon :)

**Comment by Clashsoft** [comment]
Hey, I just made a new release that should make it easier to use the library. Can you roughly tell me your setup? Are you using npm or just plain HTML? Or a framework like Angular?

**Comment by henrikfiedler** [comment]
I am using plain HTML and plain PHP. Actually I managed to download the original files from the demo page. But if there are improvements in a later release, I am curious to use it

**Comment by Clashsoft** [comment]
If you don't mind having unpkg host the files, you can use that as described in the readme. Otherwise, I put some instructions on how to build and access the css and js files in the readme as well.

**Comment by henrikfiedler** [comment]
I think some instructions would be nice. I also did some customization on the css so cdn would be a little tricky for me

**Comment by Clashsoft** [comment]
In that case you'd want to build yourself. Check [this](https://github.com/Clashsoft/bootstrap-darkmode#building-yourself) out and let me know if something is unclear.

**Comment by henrikfiedler** [comment]
Seems to work. Thank you very much. Just need to get into scss as I've never worked with that before but I'll manage that :)

**Comment by Clashsoft** [comment]
Good luck, then :) If I may ask, what kind of changes are you planning to make?

**Comment by henrikfiedler** [comment]
Works great, yes! :)
In general a much darker bg-color, lighter text-color. Some changes for the dropdown. E.g. so hover won't overwrite active styling. Different styling for readonly inputs. And also a grey styling for the <hr> as it's pretty much invisible on dark bg without customization

**Comment by Clashsoft** [comment]
Ah ok, feel free to customize to your needs. If you find something that needs improvement and is widely applicable, I'd appreciate a pull request. Or if you want me to prioritise some of the components that I didn't implement yet, let me know!
