### ISSUE TITLE
Navbar & sidebar are not changing to dark

### ISSUE THREAD

**Issue by virtumbe** [Clashsoft/bootstrap-darkmode#21]
First of all, a big thank you to the creators of this framework.

Implemented this framework on my website, everything changes to 'dark' when clicking a link (and vice versa) but not my navbar and sidebar. Already looked at the examples and I really don't see a difference (despite perhaps the customizing).

**Navbar**

```html
<script src="https://unpkg.com/bootstrap-darkmode@0.7.0/dist/theme.js"></script>
	<script>
		const themeConfig = new ThemeConfig();
		// place customizations here
		themeConfig.initTheme();
	</script>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container" style="width:80%">
			<div class="navbar-header">
...
```

**Sidebar**

```html
<script src="https://unpkg.com/bootstrap-darkmode@0.7.0/dist/theme.js"></script>
      <script>
		const themeConfig = new ThemeConfig();
		// place customizations here
		themeConfig.initTheme();
	</script>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 col-sm-12 bg-light sidebar">
          <div class="sidebar-sticky">
...
```

Do you guys spot the problem or is this a bug in the framework?

**Comment by Clashsoft** [comment]
There are no special colors for `bg-light` in darkmode, because imo it's not intuitive to change it to always be dark. However, you can add the `bg-darkmode-dark` class to make it dark only in darkmode.

Unfortunately there is no equivalent for `navbar-light`. Please let me know if it works without that, otherwise I'll work on a fix.

**Comment by virtumbe** [comment]
> There are no special colors for `bg-light` in darkmode, because imo it's not intuitive to change it to always be dark. However, you can add the `bg-darkmode-dark` class to make it dark only in darkmode.
> 
> Unfortunately there is no equivalent for `navbar-light`. Please let me know if it works without that, otherwise I'll work on a fix.

Thanks for the quick respons, bg has been switched indeed to bg-dark. But the text color stays dark. Perhaps I can make a variabel in jQuery that change it to sidebar-dark and also change it too navbar-dark.
