### ISSUE TITLE
This package shouldn't be marked as `sideEffects: false`

### ISSUE THREAD

**Issue by slaweet** [Clashsoft/bootstrap-darkmode#24]
**Describe the bug**
> [unpkg.com/browse/bootstrap-darkmode@0.9.0/package.json#L33](https://unpkg.com/browse/bootstrap-darkmode@0.9.0/package.json#L33)
> 
> Bug in `bootstrap-darkmode`. CSS files _are_ side effects. It shouldn't be marked as `sideEffects: false`.
> 
> I guess it's set by default by `ng-packagr`, but that's not a correct default for a CSS package.

Source: https://github.com/vuejs/vue-cli/issues/6628#issuecomment-895020810

**To Reproduce**
See "Steps to reproduce" in https://github.com/vuejs/vue-cli/issues/6628

**Expected behavior**
See "What is expected?" in https://github.com/vuejs/vue-cli/issues/6628

**Screenshots**
See https://github.com/vuejs/vue-cli/issues/6628

**Desktop (please complete the following information):**
 - OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
 - Browser Chrome: 92.0.4515.107
 - Version 92.0.4515.107

But any other desktop and browser would AFAIK do the same

**Comment by Clashsoft** [comment]
Looking into Webpack docs, I found this: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

It probably makes sense to add

```json
  "sideEffects": ["**/*.css", "**/*.scss"],
```

@slaweet Do you think that will fix your issue? If so maybe you can try modifying your local copy of `package.json` in `node_modules` first.

**Comment by slaweet** [comment]
@Clashsoft thank you for such a quick response.

> ```json
>   "sideEffects": ["**/*.css", "**/*.scss"],
> ```

I tested it and it works great for me.

**Comment by Clashsoft** [comment]
Fixed in v0.9.1.
